name: Build C++ Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++  # Install CMake and compiler

      - name: List repository files (for debugging)
        run: ls -R  # List all files to verify structure

      - name: Build all C++ topic folders
        run: |
          for dir in $(find . -mindepth 2 -name "CMakeLists.txt" -exec dirname {} \;); do
            echo "Building $dir..."
            mkdir -p $dir/build
            cd $dir/build
            cmake ..
            cmake --build .
            cd -  # Return to root directory
          done

