name: Build C++ Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Build and Test all C++ topics
        run: |
          find . -mindepth 2 -name "CMakeLists.txt" -print0 | while IFS= read -r -d '' cmake_file; do
            topic_dir=$(dirname "$cmake_file")
            echo "Processing: $topic_dir"

            build_dir="$topic_dir/build"
            mkdir -p "$build_dir" && cd "$build_dir"

            cmake .. && cmake --build . && ctest --output-on-failure || true
            cd - > /dev/null  # Go back to root without printing path
          done

